### ISSUE TITLE
Working with the new Docker for Mac

### ISSUE THREAD

**Issue by cmbaxter** [typesafehub/sbt-conductr#169]
I noticed that the sandbox will run fine if you install Docker Toolbox as that installs docker-machine and VirtualBox, but it will not run if you install the new Docker for Mac as that has a different virtualization system (not VirtualBox).  Any plans to get the sandbox working regardless of the underlying virtualization system?

**Comment by huntc** [comment]
Thanks for reporting. Is this with the latest CLI installed? We did some fixes before. 

https://github.com/typesafehub/conductr-cli

**Comment by dnvriend** [comment]
I have the same problem. I have docket-platform for mac installed, which is available @ localhost. I also have Virtualbox + docker combo (from way back) installed as the sandbox creates a VM called 'default'. To make the CLI work with the sandbox you'll need to append --ip $(docker-machine ip default) to all 'conductr' CLI commands. But the sbt-conductr plugin has (AFAIK) no option to set the ip address of the running sandbox. It keeps defaulting to localhost. There were some PR like [sbt-conductr - PR#117 - Resolve conductr host address more intelligent](https://github.com/typesafehub/sbt-conductr/pull/117) and [sbt-conductr-sandbox - PR#50 - Use sbt-conductr to resolve conductr ip](https://github.com/typesafehub/sbt-conductr-sandbox/pull/50), but I see that PR #117 from the sbt-conductr project didn't make it in v2.1.8, which is a shame because that would definitely fix the issue. This effectively makes it impossible for me to use conductr sandbox. 

I can get sandbox to work on docker-platform (which is the 'almost-native' version of docker), but the embedded proxy server gets all messed up when I want to connect to a simple helloworld http service (using akka-http). The request is forwarded but for some reason the connection is closed.. 

I wanted to try it on Virtualbox ie. the sandbox environment, but sbt doesnt want to deploy because AFAIK there is no way to tell it that it must not use 127.0.0.1. 

A debug from the console:

```
> conduct info
Error: Unable to contact ConductR.
Error: Reason: HTTPConnectionPool(host='127.0.0.1', port=9005): Max retries exceeded with url: /bundles (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x104199b38>: Failed to establish a new connection: [Errno 61] Connection refused',))
Error: Start the ConductR sandbox with: sandbox run IMAGE_VERSION
```

Maybe someone else has a clue or hint?

**Comment by cmbaxter** [comment]
I was able to get the sandbox running with Docker for Mac using version 1.1.18 where I had been using 1.1.18-rc3 before.  But another issue is that you don't allow any additional control for supplying things like links or a network to run on when starting the conductr nodes.  This makes it difficult to setup inter-container networking if I want apps running on my local conductr sandbox to be able to talk to say cassandra which is running in a separate container.  I suppose I could just start the conductr container's myself and have more control.  Is there a better solution?

**Comment by huntc** [comment]
Firstly the CONDUCTR_IP can be set to point the CLI and therefore sbt-conductr at a ConductR host. 

The sandbox is essentially a docker run command. You can use `docker ps --no-trunc` to grab the command such that you can tailor it for your needs. If you start the sandbox up from out sbt-conductr it will utilise it.

**Comment by dnvriend** [comment]
Thanks for the explanation/hints. Tinkering on...

**Comment by huntc** [comment]
@cmbaxter Is this issue also resolved for you now?

**Comment by cmbaxter** [comment]
Sort of.  I got the inter container networking issue resolved by using the address assigned to the default bridge network (172.17.0.1).  This allowed me to communicate properly from the ConductR containers and my Cassandra and Elasticsearch containers.  I will close.
